services:
  getbiji-dify-adapter:
    container_name: getbiji-dify-adapter
    ports:
      - "$PORT:$PORT"
    image: yufeiyohi/getbiji-dify-adapter:latest
    env_file:
      - .env
    restart: unless-stopped